### ISSUE TITLE
Python dataclasses

### ISSUE THREAD

**Issue by anthonyscorrea** [thatGuySpectre/pykanka#3]
Any reason not to use python dataclasses? I can help migrate, but don't want to presume.

I don't really think this is an issue, it's a question/suggestion, please let me know if there's a better place to put things like this, still a little new to contributing.

**Comment by thatGuySpectre** [comment]
Nope, I just wasn't aware they existed. After looking into it a bit, they indeed seem like a more elegant solution. I'll create a new branch and get to changing it when I have the time, but it seems like it should be easy to do. Thanks for the suggestion! Feel free to help, if you want to. 

I think issues is the right place to put suggestions like this, but I'm new to contributions as well, so who knows ¯\\_(ツ)_/¯
